# Generated by Django 3.1 on 2020-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200830_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='selected_image',
            field=models.CharField(choices=[(1, 'https://cdn.mos.cms.futurecdn.net/ahevYTh9pWRzkNPF85MQhb.jpg')], default=(1, 'https://cdn.mos.cms.futurecdn.net/ahevYTh9pWRzkNPF85MQhb.jpg'), max_length=255),
        ),
    ]
