# Generated by Django 3.1 on 2020-08-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200830_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='selected_image',
        ),
    ]
