# Generated by Django 3.1 on 2020-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productimage_selected_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='selected_image',
            field=models.CharField(blank=True, choices=[('1', 'https://cdn.mos.cms.futurecdn.net/ahevYTh9pWRzkNPF85MQhb.jpg')], max_length=255, null=True),
        ),
    ]
