# Generated by Django 3.1 on 2020-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productimage_selected_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='selected_image',
            field=models.IntegerField(blank=True, choices=[(1, 'https://cdn.mos.cms.futurecdn.net/ahevYTh9pWRzkNPF85MQhb.jpg')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='selected_product',
            field=models.IntegerField(blank=True, choices=[(1, 'Laptop'), (2, 'Monitor'), (3, 'Mouse'), (4, 'tastatura')], max_length=255, null=True),
        ),
    ]
