# Generated by Django 3.1 on 2020-08-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200830_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='selected_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='upload_to',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/no-thumbnail-image-placeholder-forums-blogs-websites-148010362.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='selected_product',
            field=models.IntegerField(blank=True, choices=[(1, 'Laptop'), (2, 'Monitor'), (3, 'Mouse'), (4, 'tastatura')], null=True),
        ),
    ]
